title: EASC Index
description: >-
  Welcome to the EASC standards index site!
paginate: 100
jekyll-index:
  favicon: 'https://www.relaton.org/favicon.ico'
  source: 'index-v2.yaml'
  baseurl: 'https://raw.githubusercontent.com/relaton/relaton-data-easc/main/'
  add_type_to_reference: true
  pubid_class: 'Pubid::Easc::Identifier'
  pubid_require: 'pubid'
