title: IEEE Index
description: >-
  Welcome to the IEEE standards index site!
paginate: 100
jekyll-index:
  favicon: 'https://www.relaton.org/favicon.ico'
  source: 'index-v2.yaml'
  baseurl: 'https://raw.githubusercontent.com/relaton/relaton-data-ieee/v2/'
  add_type_to_reference: true
  pubid_class: 'Pubid::Ieee::Identifier'
  pubid_require: 'pubid'
