title: ITU-R Index
description: >-
  Welcome to the ITU-R standards index site!
paginate: 100
jekyll-index:
  favicon: 'https://www.relaton.org/favicon.ico'
  source: 'index-v2.yaml'
  baseurl: 'https://raw.githubusercontent.com/relaton/relaton-data-itu-r/v2/'
  add_type_to_reference: true
  pubid_class: 'Pubid::Itu::Identifier'
  pubid_require: 'pubid'
