title: W3C Index
description: >-
  Welcome to the World Wide Web Consortium standards index site! This is where you can find the information you need about the various standards developed and maintained by the W3C open community.
paginate: 100
jekyll-index:
  favicon: 'https://www.w3.org/assets/logos/w3c/w3c-no-bars.svg'
  source: 'index-v1.yaml'
  baseurl: 'https://raw.githubusercontent.com/relaton/relaton-data-w3c/v2/'
  add_type_to_reference: true
  pubid_class: 'Relaton::W3c::PubId'
  pubid_require: 'relaton/w3c/pubid'
