require "date"
require "erb"
require "set"
require "yaml"

# Reads `cimas-config/cimas.yml`, the mapping that says which template Cimas
# copies into which file of which relaton repo.
#
# One command consumes it:
#
#   bin/cimas-orphan-audit -> #findings and #orphans, the gate that must pass
#                             before anyone runs `cimas cleanup-orphan-files`.
#
# The class exists because `cimas cleanup-orphan-files` deletes a file on a
# two-part rule, and neither part is visible in this repo:
#
#   1. the file's first 500 bytes carry `Auto-generated by Cimas`, so Cimas
#      wrote it at some point, and
#   2. the file's path is not a key of that repo's `files:` mapping, so Cimas
#      no longer regenerates it.
#
# Dropping a mapping therefore arms a delete in every destination repo that
# still holds the file. `#findings` reproduces the rule over file bodies the
# caller supplies, so the decision is testable without a network and without a
# clone of 98 repos. See relaton/support#65.
#
# The constants below mirror `Cimas::GENERATED_HEADER`, `Cimas::OrphanFiles`
# and `Cimas::Repository` in the cimas gem. The gem is not a dependency of this
# repo, so they are restated here and pinned by spec/cimas_config_spec.rb.
class CimasConfig
  DEFAULT_CONFIG_PATH =
    File.expand_path("../cimas-config/cimas.yml", __dir__).freeze

  # `CIMAS_MASTER_DIR` in the README runbook: the root the `files:` values are
  # relative to.
  DEFAULT_MASTER_PATH = File.expand_path("../cimas-config", __dir__).freeze

  # The ownership marker Cimas writes into every file it generates, and the
  # two-line header it writes it in. A file without the marker is never
  # deleted, whatever the mapping says.
  GENERATED_HEADER_MARKER = "Auto-generated by Cimas".freeze
  GENERATED_HEADER = [
    "# #{GENERATED_HEADER_MARKER}: Do not edit it manually!",
    "# See https://github.com/metanorma/cimas",
  ].join("\n").freeze

  # Bytes Cimas reads per file when it looks for the marker. A marker below
  # this cut does not make a file Cimas-managed.
  HEADER_READ_BYTES = 500

  # One row of the audit. `state` is the Cimas verdict, `template` and `match`
  # say which template the file came from and whether it still matches it.
  Finding = Struct.new(:repo, :path, :state, :template, :match,
                       keyword_init: true)

  # The comment that records a deliberate un-mapping, and the reason for it:
  #
  #   # unmapped 2026-09-03 (relaton/support#65): <reason>
  #
  # spec/cimas_unmapped_markers_spec.rb explains why an un-mapping needs one.
  MARKER_RE = %r{
    \A\s*\#\s*unmapped\s+
    (?<date>\d{4}-\d{2}-\d{2})\s+
    \((?<issue>[\w.-]+/[\w.-]+\#\d+)\):\s*\S
  }x

  attr_reader :repositories, :groups, :master

  def self.load(path = DEFAULT_CONFIG_PATH, master: DEFAULT_MASTER_PATH)
    data = YAML.safe_load_file(path)
    new(data.fetch("repositories"), data.fetch("groups", {}), master)
  end

  # True when Cimas owns this file body. `nil` is a body the audit could not
  # read; Cimas skips such a file too, so it is not owned.
  def self.generated?(content)
    return false if content.nil?

    content[0, HEADER_READ_BYTES].to_s.include?(GENERATED_HEADER_MARKER)
  end

  # Where bin/cimas-orphan-audit reads the header bytes of a file too big to
  # fetch whole. Built here rather than interpolated at the call site because a
  # destination path may hold a space: `URI.parse` raises on one, the caller's
  # `rescue StandardError` turns that into nil, and the audit then reports a
  # readable file as unreadable — which exits 1. relaton/NIST-Tech-Pubs holds a
  # 2.8 MB `NIST-TS-itables-compact (1).html`, so this is not hypothetical.
  #
  # Escaped per segment: the separators have to survive, or every nested path
  # 404s. Only the path is escaped; `slug` and `branch` come from cimas.yml.
  #
  # `ERB::Util.url_encode` rather than `URI::DEFAULT_PARSER.escape`, which
  # leaves `?` and `&` raw — a file named `a?b.html` would then split into a
  # path and a query string and fetch the wrong thing. Not `CGI.escape` either:
  # it writes a space as `+`, which in a path means a literal plus.
  #
  # A path that already contains a percent is encoded again, on purpose: these
  # come from a GitHub contents listing, so `%20` there is a literal percent,
  # two and a zero in the filename.
  def self.raw_url(slug, branch, path)
    escaped = path.split("/").map { |seg| ERB::Util.url_encode(seg) }.join("/")
    "https://raw.githubusercontent.com/#{slug}/#{branch}/#{escaped}"
  end

  # Reads the `files:` blocks of a cimas.yml as text, and reports every place
  # the un-mapping convention applies. YAML drops comments, so this walks the
  # lines.
  #
  # Each result is one place a reason is owed:
  #
  #   kind: :comment - a comment inside a `files:` block that still maps files
  #   kind: :empty   - a `files:` block that maps nothing at all
  #
  # `marked` says whether a MARKER_RE line covers it. A comment line directly
  # below a marker continues it and raises nothing of its own.
  def self.scan_unmapped(text)
    Scanner.new(text).call
  end

  # The line walker behind .scan_unmapped. Split out so the state it carries
  # between lines stays private to the scan.
  class Scanner
    REPOSITORIES_RE = /\A\s*repositories:\s*\z/
    # A top-level key other than `repositories:` ends the walk. `groups:` holds
    # `  sites:` lines that REPO_RE would otherwise read as repo entries.
    TOP_LEVEL_RE = /\A\S/
    REPO_RE = /\A {2}(?<name>[\w.-]+):\s*\z/
    # `files:` with nothing after it, or with an empty mapping or list on the
    # same line. Cimas reads all three as "this repo maps no file", so all
    # three owe a reason.
    FILES_RE = /\A {4}files:\s*(?<inline>\{\s*\}|\[\s*\])?\s*\z/
    COMMENT_RE = /\A\s*\#/
    BLANK_RE = /\A\s*\z/

    def initialize(text)
      @lines = text.lines
      @results = []
      @repo = nil
      @saw_files = false
      reset_block
    end

    def call
      in_repositories = false
      @lines.each_with_index do |line, index|
        if REPOSITORIES_RE.match?(line)
          in_repositories = true
          next
        end
        if in_repositories && TOP_LEVEL_RE.match?(line)
          close_repo
          in_repositories = false
        end
        next unless in_repositories

        handle(line, index + 1)
      end
      close_repo
      @results
    end

    private

    def handle(line, number)
      if (repo = REPO_RE.match(line))
        close_repo
        @repo = repo[:name]
      elsif FILES_RE.match?(line)
        close_block
        @in_files = true
        @saw_files = true
      elsif @in_files
        handle_in_files(line, number)
      end
    end

    # A repo entry with no `files:` key at all maps nothing, the same as one
    # with an empty `files:`, so it owes the same reason.
    def close_repo
      had_files = @saw_files
      repo = @repo
      close_block
      @saw_files = false
      # Cleared so a second close of the same repo — the one at the end of the
      # walk, after the `groups:` boundary already closed it — reports nothing.
      @repo = nil
      return if had_files || repo.nil?

      @results << { repo: repo, kind: :empty, line: nil, marked: false,
                    date: nil, issue: nil }
    end

    def handle_in_files(line, number)
      return if BLANK_RE.match?(line)
      # The block ends at the first line that is not indented into it. A
      # comment at a shallower indent is a section heading between two repo
      # entries, not a note about this mapping.
      return close_block unless line.start_with?(" " * 6)

      if COMMENT_RE.match?(line)
        handle_comment(line, number)
      else
        @mappings += 1
        @in_marker = false
      end
    end

    def handle_comment(line, number)
      if (marker = MARKER_RE.match(line))
        @marker ||= { date: marker[:date], issue: marker[:issue], line: number }
        @comments << { line: number, marked: true,
                       date: marker[:date], issue: marker[:issue] }
        @in_marker = true
      elsif !@in_marker
        @comments << { line: number, marked: false, date: nil, issue: nil }
      end
    end

    # A block that maps nothing owes one reason for the whole repo; a block
    # that still maps files owes one for each comment that is not a marker.
    def close_block
      if @in_files && @repo
        if @mappings.zero?
          @results << { repo: @repo, kind: :empty, line: @marker&.fetch(:line),
                        marked: !@marker.nil?, date: @marker&.fetch(:date),
                        issue: @marker&.fetch(:issue) }
        else
          @comments.each { |c| @results << c.merge(repo: @repo, kind: :comment) }
        end
      end
      reset_block
    end

    def reset_block
      @in_files = false
      @in_marker = false
      @mappings = 0
      @comments = []
      @marker = nil
    end
  end

  def initialize(repositories, groups, master)
    @repositories = repositories
    @groups = groups
    @master = master
  end

  def names
    repositories.keys
  end

  def entry(name)
    raise ArgumentError, "unknown repo #{name.inspect}" unless repositories.key?(name)

    repositories.fetch(name) || {}
  end

  # Destination path -> template path. Cimas::Repository reads three shapes and
  # normalises the first two to an empty mapping: no value, an empty list, and
  # a mapping. An empty mapping makes every Cimas-written file in that repo an
  # orphan, so the empty shapes matter as much as the full one.
  def files(name)
    raw = entry(name)["files"]
    raw.is_a?(Hash) ? raw : {}
  end

  def mapped_targets(name)
    files(name).keys
  end

  def branch(name)
    entry(name)["branch"]
  end

  # The GitHub slug, taken from `remote:`. Two keys do not match their repo
  # name (`loc_marc` and `loc_mods`), so the key is not an address.
  def slug(name)
    remote = entry(name)["remote"].to_s
    match = remote.match(%r{[/:]([\w.-]+)/([\w.-]+?)(?:\.git)?\z})
    raise ArgumentError, "unparseable remote for #{name.inspect}: #{remote.inspect}" unless match

    "#{match[1]}/#{match[2]}"
  end

  # `cimas -g` semantics: a group name, a repo name, or `all`. An empty
  # selection is every repo, because the audit mutates nothing.
  def resolve(selectors)
    list = Array(selectors)
    return names if list.empty? || list.include?("all")

    list.flat_map do |selector|
      if groups.key?(selector)
        Array(groups[selector])
      elsif repositories.key?(selector)
        [selector]
      else
        raise ArgumentError, "unknown repo or group #{selector.inspect}"
      end
    end.uniq
  end

  # Repos no group lists. `cimas -g <group>` never reaches them, so a wave
  # scoped by group and one scoped by `all` delete different files.
  def ungrouped
    grouped = groups.values.flat_map { |list| Array(list) }.to_set
    names.reject { |name| grouped.include?(name) }
  end

  def all_target_paths
    names.flat_map { |name| mapped_targets(name) }.uniq.sort
  end

  # Every template any repo copies to this destination path. Usually one.
  #
  # Cimas also accepts a mapping value of `{if_public:, if_private:}` and picks
  # the branch at sync time from the target repo's visibility. No entry uses
  # that shape, and this class cannot read a repo's visibility, so such a value
  # is skipped rather than guessed.
  def templates_for(path)
    names.filter_map { |name| files(name)[path] }.grep(String).uniq
  end

  def template_path(src)
    File.join(master, src)
  end

  # What `cimas sync` writes into a destination: the header, then the template
  # body. `copy_file` uses File.foreach + puts, so a template with no final
  # newline gains one.
  #
  # Cimas renders an `.erb` template instead of copying it. No template here is
  # `.erb`, and this affects only the `same` / `diverged` note in the audit
  # table, never whether a file is an orphan.
  def synced_body(src)
    body = File.read(template_path(src))
    body += "\n" unless body.end_with?("\n")
    "#{GENERATED_HEADER}\n#{body}"
  end

  # Judge a destination repo. `blobs` is `path => body`, the files the caller
  # fetched; a nil body is a file it could not read.
  #
  #   :orphan    - Cimas wrote it and no longer maps it. The wave deletes it.
  #   :mapped    - Cimas wrote it and still maps it. The wave keeps it.
  #   :unmanaged - no header. The wave never touches it.
  def findings(name, blobs, only_targets: nil)
    mapped = mapped_targets(name).to_set
    wanted = only_targets && Array(only_targets).to_set

    blobs.filter_map do |path, body|
      next if wanted && !wanted.include?(path)

      state = if !self.class.generated?(body)
                :unmanaged
              elsif mapped.include?(path)
                :mapped
              else
                :orphan
              end
      Finding.new(repo: name, path: path, state: state,
                  **template_match(path, body))
    end
  end

  def orphans(name, blobs, only_targets: nil)
    findings(name, blobs, only_targets: only_targets)
      .select { |finding| finding.state == :orphan }
  end

  private

  # Which template this path came from, and whether the file still matches it.
  # A path no repo maps has no template to compare against.
  def template_match(path, body)
    src = templates_for(path).find { |candidate| File.exist?(template_path(candidate)) }
    return { template: nil, match: nil } unless src

    { template: src, match: body == synced_body(src) ? :same : :diverged }
  end
end
