name: make

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  make:
    name: Test on PlantUML ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - uses: metanorma/metanorma-build-scripts/plantuml-setup-action@master

      - run: make clean all
