name: check_data

on:
  workflow_call:

jobs:
  check-data:
    name: Test on Ruby ${{ matrix.ruby }} Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # workaround for https://github.com/actions/runner-images/issues/37
      - run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec ruby check_data.rb
