name: crawler

on:
  workflow_call:
    inputs:
      args:
        description: Extra args to pass to crawler.rb script
        required: false
        default: ''
        type: string

jobs:
  crawl:
    name: Documents fetching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec ruby crawler.rb ${{ inputs.args }}

      - name: Diff data
        id: diff
        run: |
          [ -d data ] && echo data/* | xargs git add

          if [ -f index.yaml ]; then
            zip index.zip index.yaml
            git add index.zip index.yaml
          fi

          if git diff --cached --exit-code
          then
            echo "Data not changed. Skip commit"
            echo "skip_commit=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "skip_commit=false" >> $GITHUB_OUTPUT

      - if: github.event_name != 'pull_request' && steps.diff.outputs.skip_commit != 'true'
        name: Push data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
