name: crawler

on:
  workflow_call:
    inputs:
      args:
        description: Extra args to pass to crawler.rb script.
        required: false
        default: ''
        type: string
      override-files:
        description: Override files (with wget). Format url=path (multiline).
        required: false
        default: ''
        type: string
      fetch-command:
        description: >
          The Command that performs data fetch and 'git commit' data.
          The `args` input will be passed as arguments to `fetch-command`
          If needed files in 'data' directory can be removed in the beginning of the script
          Any files except 'data/*', index.yaml have to be committed explicitly
        required: false
        default: 'bundle exec ruby crawler.rb'
        type: string
      commit-indexes:
        description: >
          Defines whether index files should be committed to the repository or not.
        required: false
        default: true
        type: boolean
    secrets:
      args:
        description: Extra args to pass to crawler.rb script
        required: false

jobs:
  crawl:
    name: Documents fetching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          while read line
          do
            if [ "$line" = "" ]
            then
              continue
            fi
            url=${line%=*}
            path="${line#*=}"
            mkdir -p $(dirname "${path}")
            wget "${url}" -O "${path}"
          done <<< "${{ inputs.override-files }}"
        shell: bash

      # workaround for https://github.com/actions/runner-images/issues/37
      - run: sudo apt-get install libcurl4-openssl-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: ${{ !contains(inputs.override-files, 'Gemfile') }}

      - if: contains(inputs.override-files, 'Gemfile')
        run: |
          bundle config unset --local deployment
          bundle install

      - run: |
          ${{ inputs.fetch-command }} ${{ inputs.args }} ${{ secrets.args }}

      - name: Diff data
        id: diff
        run: |
          [ -d data ] && echo data/* | xargs git add
          git add -u data/
          
          if ${{ inputs.commit-indexes }}
          then
            shopt -s nullglob # https://stackoverflow.com/a/31054582/902217
            for yaml in index*.yaml; do
              zip_name="${yaml%.*}.zip"
              zip "${zip_name}" "${yaml}"
              git add "${zip_name}" "${yaml}"
            done
          fi

          if git diff --cached --exit-code
          then
            echo "Data not changed. Skip commit"
            echo "skip_commit=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "skip_commit=false" >> $GITHUB_OUTPUT

      - if: github.event_name != 'pull_request' && steps.diff.outputs.skip_commit != 'true'
        name: Push data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
