name: Deploy

on:
  workflow_call:

jobs:
  build_index_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          cache-version: 0

      - uses: actions/checkout@v4
        with:
          repository: relaton/jekyll-theme-relaton-data-index
          path: src

      - name: Merge _config.yml
        shell: python
        run: |
          import os
          import yaml

          base_config_path = 'src/_config.yml'
          repo_config_path = '_config.yml'

          with open(base_config_path) as base_config_file, open(repo_config_path) as config_file:
            base_config = yaml.safe_load(base_config_file)
            config = yaml.safe_load(config_file)

          result_config = {**base_config, **config}

          with open(repo_config_path, 'w') as file:
            yaml.dump(result_config, file)

          os.remove(base_config_path)

      - run: |
          cat _config.yml
          echo "---"
          tree src

      - id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    needs: build_index_page

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4