name: lint

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: yaml lint
        run: |
          sudo apt-get install yamllint
          yamllint cimas-config/
