name: rake

on:
  workflow_call:

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1']
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # https://github.com/ruby-debug/debase/issues/89#issuecomment-686827382
      - if: matrix.os == 'macos-latest' && matrix.ruby == '2.5'
        run: echo BUNDLE_BUILD__DEBASE="--with-cflags=\"-Wno-error=implicit-function-declaration\"" >> $GITHUB_ENV

      # https://github.com/rubygems/rubygems/issues/4360#issuecomment-775075740
      - if: matrix.ruby == '3.0'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          rubygems: latest

      - if: matrix.ruby != '3.0'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
